@startuml
interface Contact {
    +contactCode: string
    +contactKey: string
    +leaseIds?: string[]
    +leases?: Lease[]
    +firstName: string
    +lastName: string
    +fullName: string
    +nationalRegistrationNumber: string
    +birthDate: Date
    +address: Address
    +phoneNumbers: PhoneNumber[]
    +emailAddress: string
    +isTenant: boolean
}
interface PhoneNumber {
    +phoneNumber: string
    +type: string
    +isMainNumber: boolean
}
interface Lease {
    +leaseId: string
    +leaseNumber: string
    +leaseStartDate: Date
    +leaseEndDate: Date
    +status: LeaseStatus
    +tenantContactIds: string[]
    +tenants: Contact[]
    +rentalPropertyId: string
    +rentalProperty: RentalProperty
    +type: string
    +rentInfo: RentInfo
    +address: Address
    +noticeGivenBy: string
    +noticeDate: Date
    +noticeTimeTenant: string
    +preferredMoveOutDate: Date
    +terminationDate: Date
    +contractDate: Date
    +lastDebitDate: Date
    +approvalDate: Date
    +residentialArea?: ResidentialArea
}
interface ResidentialArea {
    +code: string
    +caption: string
}
interface RentalProperty {
    +rentalPropertyId: string
    +apartmentNumber: number
    +size: number
    +type: string
    +address: Address
    +rentalPropertyType: string
    +additionsIncludedInRent: string
    +otherInfo: string
    +roomTypes: RoomType[]
    +lastUpdated: Date
}
interface Address {
    +street: string
    +number: string
    +postalCode: string
    +city: string
}
interface RentInfo {
    +currentRent: Rent
    +futureRents: Rent[]
}
interface Rent {
    +rentId?: string
    +leaseId?: string
    +currentRent: number
    +vat: number
    +additionalChargeDescription: string
    +additionalChargeAmount: number
    +rentStartDate: Date
    +rentEndDate: Date
}
interface RoomType {
    +roomTypeId: string
    +name: string
    +materialOptionGroups?: MaterialOptionGroup[]
}
interface MaterialChoice {
    +materialChoiceId: string
    +materialOptionId: string
    +materialOptionGroupId: string
    +apartmentId: string
    +roomTypeId: string
    +materialOption?: MaterialOption
    +materialOptionGroup?: MaterialOptionGroup
    +roomType?: RoomType
    +status: string
    +dateOfSubmission?: Date
    +dateOfCancellation?: Date
}
interface MaterialOptionGroup {
    +materialOptionGroupId: string
    +roomTypeId: string
    +roomTypeName?: string
    +name?: string
    +actionName?: string
    +materialOptions?: MaterialOption[]
    +materialChoices?: MaterialChoice[]
    +type: string
}
interface MaterialOption {
    +materialOptionId: string
    +caption: string
    +shortDescription?: string
    +description?: string
    +coverImage?: string
    +images?: string[]
    +roomTypeName?: string
    +materialOptionGroupName?: string
}
interface ConsumerReport {
    +pnr: string
    +template: string
    +status: string
    +status_text: string
    +errorList: ConsumerReportError[] | []
    +name: string
    +address: string
    +zip: string
    +city: string
}
interface ConsumerReportError {
    +Cause_of_Reject: string
    +Reject_text: string
    +Reject_comment: string
}
interface ParkingSpace {
    +parkingSpaceId: string
    +address: Address
    +rent: RentInfo
    +vacantFrom: Date
    +type: ParkingSpaceType
    +applicationCategory: ParkingSpaceApplicationCategory
}
interface Email {
    +to: string
    +subject: string
    +text: string
}
interface Invoices {
    +unpaidInvoices?: Invoice[]
    +paidInvoices?: Invoice[]
}
interface Invoice {
    +invoiceId: string
    +leaseId: string
    +amount: number
    +fromDate: Date
    +toDate: Date
    +invoiceDate: Date
    +expirationDate: Date
    +debitStatus: number
    +paymentStatus: PaymentStatus
    +transactionType: InvoiceTransactionType
    +transactionTypeName: string
    +paidAmount?: number
    +daysSinceLastDebitDate?: number
}
interface WaitingList {
    +applicantCaption: string
    +contactCode: string
    +contractFromApartment: Date
    +queuePoints: number
    +queuePointsSocialConnection: number
    +waitingListFrom: Date
    +waitingListTypeCaption: string
}
interface Listing {
    +id: number
    +rentalObjectCode: string
    +address: string
    +monthlyRent: number
    +districtCaption?: string
    +districtCode?: string
    +blockCaption?: string
    +blockCode?: string
    +objectTypeCaption?: string
    +objectTypeCode?: string
    +rentalObjectTypeCaption?: string
    +rentalObjectTypeCode?: string
    +publishedFrom: Date
    +publishedTo: Date
    +vacantFrom: Date
    +status: ListingStatus
    +waitingListType?: string
    +applicants?: Applicant[]
}
interface Applicant {
    +id: number
    +name: string
    +nationalRegistrationNumber: string
    +contactCode: string
    +applicationDate: Date
    +applicationType?: string
    +status: ApplicantStatus
    +listingId: number
}
interface Offer {
    +id: number
    +sentAt: Date
    +expiresAt: Date
    +answeredAt: Date
    +selectedApplicants: Applicant[]
    +status: OfferStatus
    +listingId: number
    +offeredApplicant: Applicant
}
interface ApplicantWithListing {
    +applicant: Applicant
    +listing: Listing
}
interface RentalPropertyInfo {
    +id: string
    +type: string
    +property: ApartmentInfo | CommercialSpaceInfo | ParkingSpaceInfo
    +maintenanceUnits?: MaintenanceUnitInfo[]
}
interface ApartmentInfo {
    +rentalTypeCode: string
    +rentalType: string
    +address: string
    +code: string
    +number: string
    +type: string
    +entrance: string
    +floor: string
    +hasElevator: boolean
    +washSpace: string
    +area: number
    +estateCode: string
    +estate: string
    +buildingCode: string
    +building: string
}
interface CommercialSpaceInfo {
    +rentalTypeCode: string
    +rentalType: string
    +address: string
    +code: string
    +type: string
    +entrance: string
    +estateCode: string
    +estate: string
    +buildingCode: string
    +building: string
}
interface ParkingSpaceInfo {
    +rentalTypeCode: string
    +rentalType: string
    +address: string
    +code: string
}
interface MaintenanceUnitInfo {
    +id: string
    +rentalPropertyId: string
    +code: string
    +caption: string
    +type: string
    +estateCode: string
    +estate: string
}
interface SystemHealth {
    +name: string
    +status: SystemStatus
    +subsystems?: SystemHealth[]
    +statusMessage?: string
}
@enduml